// react_cli/src/App.jsx
import React, { Suspense, lazy } from "react";
import { Link, Routes, Route } from "react-router-dom";
import { Button } from "antd";
// import Home from "./page/Home";
// import About from "./page/About";

// 路由懒加载
const Home = lazy(() => import(/* webpackChunkName: 'home' */ "./page/Home"));
const About = lazy(() =>
  import(/* webpackChunkName: 'about' */ "./page/About")
);

function App() {
  return (
    <div>
      <h1>App</h1>
      <Button type="primary">按钮</Button>
      <ul>
        <li>
          <Link to="/home">Home</Link>
        </li>
        <li>
          <Link to="/about">About</Link>
        </li>
      </ul>
      <Suspense fallback={<div>loading</div>}>
        <Routes>
          <Route path="/home" element={<Home />}></Route>
          <Route path="/about" element={<About />}></Route>
        </Routes>
      </Suspense>
      {/* <About /> */}
    </div>
  );
}

export default App;

// vue_cli/src/App.vue
<template>
  <h1 class="title">hello app</h1>
  <el-button type="primary">按钮</el-button>
  <ul>
    <li>
      <router-link to="/home">Home</router-link>
    </li>
    <li>
      <router-link to="/about">About</router-link>
    </li>
  </ul>

  <RouterView />
</template>

<script>
import { ElButton } from 'element-plus';
export default {
  name: 'App',
  components: {
    ElButton,
  },
};
</script>

<style>
.title {
  color: pink;
}
</style>
